### ISSUE TITLE
new ioctl like BIO_IOCTL_GET_MEM_MAP with no side effects

### ISSUE THREAD

**Issue by cpu-chromium** [travisg/lk#73]
Issuing ioctl with BIO_IOCTL_GET_MEM_MAP for qspi causes it to enter into linear mode, it would be nice to have an ioctl which gives me the address it would be mapped to but without causing it to enter linear mode, so I can get the address it would map.

**Comment by gkalsi** [comment]
Closing. Fixed by #74
