### ISSUE TITLE
lib/bio needs C guards (__BEGIN_CDECL)

### ISSUE THREAD

**Issue by cpu-chromium** [travisg/lk#76]
From a cpp file:
 #include <lib/bio.h>

Generates errors of the form:
foo_runner.cpp:33: undefined reference to `bio_open(char const*)'
foo_runner.cpp:39: undefined reference to `bio_ioctl(bdev*, int, void*)'

which go away if you do

extern "C" {
#include <lib/bio.h>
}

**Comment by gkalsi** [comment]
Fixed by 4560219c452f78c7d35d2a8d13634056503594f5
